### ISSUE TITLE
Syntax Highlighting Broken in Xcode 11

### ISSUE THREAD

**Issue by JakeTorres** [apollographql/xcode-graphql#23]
installed GraphQL.ideplugin in Xcode11, can't get highlight now

**Comment by Vuong-Dao** [comment]
Yes. I got the same problem on Xcode 11 from App Store

**Comment by amadeu01** [comment]
+1

**Comment by designatednerd** [comment]
Looking into this - it seems like [at least one other syntax highlighting plugin](https://github.com/RobotsAndPencils/stencil-xclangspec) and is reporting that while Xcode is loading the plugin, it's not actually using the syntax highlighing spec included. :(

**Comment by adamirowe** [comment]
Same

**Comment by designatednerd** [comment]
Yeah looks like they changed a whole mess of stuff around this in Xcode 11. Whee!

I'm working on finding a better workaround, but here's a temporary one based on [this](https://forums.developer.apple.com/thread/122901) that you can use  **if you feel comfortable with messing with things within the Xcode path** (I generally don't, which is why this is a temporary workaround and not a permanent fix): 

1. Move the `GraphQL.xclangspec` file from `~/Library/Developer/Xcode/Specifications` to `/Applications/Xcode.app/Contents/SharedFrameworks/SourceModel.framework/Versions/A/Resources/LanguageMetadata`

2. Add the following as the file `Xcode.SourceCodeLanguage.GraphQL.plist` in `/Applications/Xcode.app/Contents/SharedFrameworks/SourceModel.framework/Versions/A/Resources/LanguageMetadata`: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>commentSyntaxes</key>
	<array>
		<dict>
			<key>prefix</key>
			<string>/*</string>
			<key>suffix</key>
			<string>*/</string>
		</dict>
		<dict>
			<key>prefix</key>
			<string>//</string>
		</dict>
	</array>
	<key>conformsToLanguageIdentifiers</key>
	<array>
		<string>Xcode.SourceCodeLanguage.Generic</string>
	</array>
	<key>fileDataTypeIdentifiers</key>
	<array>
		<string>com.netscape.javascript-source</string>
	</array>
	<key>identifier</key>
	<string>Xcode.SourceCodeLanguage.GraphQL</string>
	<key>isHidden</key>
	<false/>
	<key>languageName</key>
	<string>GraphQL</string>
	<key>languageSpecification</key>
	<string>xcode.lang.graphql</string>
	<key>supportsIndentation</key>
	<true/>
	<key>allowWhitespaceTrimming</key>
	<true/>
	<key>requiresHardTabs</key>
	<false/>
	<key>indentationTriggers</key>
	<array>
		<string>{</string>
		<string>}</string>
	</array>
</dict>
</plist>
```

3. Restart Xcode. 

I've found that this works, but there's 100% got to be a better way to do this which does not involve shoving stuff into Xcode's path.

**Comment by adamirowe** [comment]
Thanks for digging on this, @designatednerd. I wonder if xCode has plans to add GraphQL as an officially supported language in the editor and the file template menus, or if there's some sort of Apple vs Facebook beef that would slow that from happening.

**Comment by designatednerd** [comment]
Hopefully they've just changed where you can add this stuff from the `~/Library` path and forgotten to update the docs. I don't think it's an Apple vs. FB thing, Apollo isn't affiliated with FB, nor are a number of other open-source GQL projects. 

I suspect it probably has more to do with the change to using Language Server Protocol with Swift, but that's based on generally following stuff rather than any actual knowledge. 😇

**Comment by designatednerd** [comment]
Filed [a Feedback/Radar](https://openradar.appspot.com/radar?id=4977009499308032) to try and get some info from Apple on this.

**Comment by JakeTorres** [comment]
I tried it and it is OK according to the method you provided.

1 Move the GraphQL.xclangspec file from ~/Library/Developer/Xcode/Specifications to /Applications/Xcode.app/Contents/SharedFrameworks/SourceModel.framework/Versions/A/Resources/LanguageSpecifications

Add the following as the file Xcode.SourceCodeLanguage.GraphQL.plist in /Applications/Xcode.app/Contents/SharedFrameworks/SourceModel.framework/Versions/A/Resources/LanguageMetadata:

**Comment by interstateone** [comment]
@designatednerd Would you be interested in a PR that adds a flag to setup.sh so users could opt-in to this workaround with a command like `./setup.sh --embed-in-xcode /Applications/Xcode-11.app` or would you rather avoid that because of the fragile nature?

**Comment by designatednerd** [comment]
Appreciate the offer, but b) - I'd rather avoid it because of the fragile nature.

**Comment by evgpopov** [comment]
Not working in Xcode 11.1

**Comment by designatednerd** [comment]
Unfortunately I have not received any response from Apple about this yet, so this should be considered broken for any minor point release of Xcode 11. 😭

**Comment by gsp100677** [comment]
Didn't Apple [stop supporting plugins](https://nshipster.com/xcode-source-extensions/) some time ago, and favour [Xcode Extensions](https://developer.apple.com/documentation/xcodekit/creating_a_source_editor_extension) as the way to do things like this now?

**Comment by koenpunt** [comment]
> syntax highlighting features

I don't believe syntax highlighting is a feature of an extension.

**Comment by designatednerd** [comment]
@gsp100677 You're correct that they mostly stopped supporting plugins when Xcode 8 came out. Unfortunately Xcode extensions can't do any kind of syntax highlighting - they only really permit you to examine one file at a time and make adjustments to its contents. (If you're bored I did a [a whole talk on this three years ago](https://www.youtube.com/watch?v=0oizSiHeaGk), and unfortunately very little has changed since then). 

There's an *extremely* limited (and undocumented) subset of things that Xcode plugins can still do, but one of them is registering file types. If you look at [the only file besides the `Info.plist` in the plugin](https://github.com/apollographql/xcode-graphql/blob/master/GraphQL.ideplugin/Contents/Resources/GraphQL.xcplugindata),  you'll see it's basically telling Xcode that it should look at files with the extension .`graphql` as...GraphQL files! There's a similar plugin that does the same thing for [Kotlin](https://github.com/touchlab/xcode-kotlin) as well. 

The problem at the moment is that @koenpunt is correct - syntax highlighting is supported through a separate, also undocumented API, the one that uses the `.xclangspec` file. Previously, if you copied the `.xclangspec` to `~/Library/Developer/Xcode/Specifications/`, voila, anything recognized as a GraphQL file (which it would be after adding the plugin) would get GraphQL syntax highlighting. This piece is what broke from Xcode 10 -> 11, and what I'm waiting to hear back from Apple on to see if they intend to restore the ability to recognize this from a folder that isn't part of Xcode's path. 

Again, you can use [this workaround](https://github.com/apollographql/xcode-graphql/issues/23#issuecomment-534634008) _if you feel comfortable mucking around in Xcode's path_. 

Hope that helps explain the structure and the problem a bit better!

**Comment by jbouaziz** [comment]
For the people coming to this issue trying to find a solution for Xcode 11.2.1:
1. Do [this workaround](https://github.com/apollographql/xcode-graphql/issues/23#issuecomment-534870980)
2. Within the `GraphQL.ideplugin` > `Info.plist` file, add the following string value `A74FBA51-FFEA-4409-B976-6FC3225A6F64` in the `DVTPlugInCompatibilityUUIDs` section.
You should have a file that looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleIdentifier</key>
	<string>com.apollographql.xcode.graphql</string>
	<key>CFBundleName</key>
	<string>GraphQL Xcode Plug-in</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>DVTPlugInCompatibilityUUIDs</key>
	<array>
		<string>8A66E736-A720-4B3C-92F1-33D9962C69DF</string>
		<string>65C57D32-1E9B-44B8-8C04-A27BA7AAE2C4</string>
		<string>DA4FDFD8-C509-4D8B-8B55-84A7B66AE701</string>
		<string>E0A62D1F-3C18-4D74-BFE5-A4167D643966</string>
		<string>DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C</string>
		<string>CA351AD8-3176-41CB-875C-42A05C7CDEC7</string>
		<string>DF11C142-1584-4A99-87AC-1925D5F5652A</string>
		<string>89CB8A86-8683-4928-AF66-11A6CE26A829</string>
		<string>C3998872-68CC-42C2-847C-B44D96AB2691</string>
		<string>B395D63E-9166-4CD6-9287-6889D507AD6A</string>
		<string>EE23884D-A5C0-4163-94CF-DBBF3A5ED8D6</string>
		<string>426A087B-D3AA-431A-AFDF-F135EC00DE1C</string>
		<string>8B9F56A7-4D8B-41AA-A65D-D4906CDF1539</string>
		<string>D7881182-AD00-4C36-A94D-F45FC9B0CF85</string>
		<string>72F7D751-F810-43B8-A53F-1F1DFD74FC54</string>
		<string>B89EAABF-783E-4EBF-80D4-A9EAC69F77F2</string>
		<string>2FD51EF8-522D-4532-9698-980C4C497FD1</string>
		<string>92CB09D8-3B74-4EF7-849C-99816039F0E7</string>
		<string>A74FBA51-FFEA-4409-B976-6FC3225A6F64</string>
	</array>
	<key>XCPluginHasUI</key>
	<false/>
</dict>
</plist>
```

FYI I've used this command line to get the `UUID` ([source](https://gist.github.com/bradley219/6614b00a6e35a278176a)):
```
defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID
```

**Comment by designatednerd** [comment]
Hey @jbouaziz - that [UUID was added to this repo a while back](https://github.com/apollographql/xcode-graphql/commit/fb793764917152378d7e0a850e6e9acfd39f90cc) - it's possible you have an older version of the plugin though.

**Comment by BecomerichAsun** [comment]
Hello, I did the following but the highlighting still doesn't work！

Xcode Version 11.2.1 (11B500) 

1 Move the GraphQL.xclangspec file from ~/Library/Developer/Xcode/Specifications to /Applications/Xcode.app/Contents/SharedFrameworks/SourceModel.framework/Versions/A/Resources/LanguageSpecifications

2.Add the following as the file Xcode.SourceCodeLanguage.GraphQL.plist in /Applications/Xcode.app/Contents/SharedFrameworks/SourceModel.framework/Versions/A/Resources/LanguageMetadata:

Although it does not affect, it is always a difficult thing

**Comment by designatednerd** [comment]
@BecomerichAsun do you have the most recent version of the info.plist that has the 11.2 UUID in it locally?

**Comment by matsoft90** [comment]
Is it still broken on 11.3?

**Comment by designatednerd** [comment]
Yep - not seeing any indication this is going to get fixed anytime soon, so I will look at making the dirty hack official 🙃

**Comment by designatednerd** [comment]
Opened PR #26 to address this, gonna leave that up til the end of the day for comment then merge it if there are no objections.

**Comment by designatednerd** [comment]
Dirty hack is now in. Closing this out - if you run into problems, please open a new issue.
